nodeLinker: pnp

plugins:
  - checksum: 5e73a1acbb9741fce1e8335e243c9480ea2107b9b4b65ed7643785ddea9e3019aee254a92a853b1cd71023b16fff5b7d3afd5256fe57cd35a54f8785b8c30281
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v4.0.1/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
