nodeLinker: pnp

plugins:
  - checksum: c13ed363e15a826d9f779e7e7aca9dbee1d6d54813261d6f495da2fa94b01fa7579e516587ae2df5834f5d63d5d90cb392135190e8878b81dbd830c3c9f57809
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v4.0.2/bundles/@yarnpkg/plugin-outdated.js"
  - path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/main/index.js"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
